### ISSUE TITLE
如何支持Presto

### ISSUE THREAD

**Issue by phillip2019** [ClouGence/hasor#111]
报错如下，看源代码不存在presto dialect
2021-11-06 16:50:23.917 [http-nio-8080-exec-3] ERROR n.h.dataway.service.ApiCallService - [line 6:13~10:2 ,QIL 1:6] load dialect 'presto' class not found
net.hasor.dataql.runtime.QueryRuntimeException: [line 6:13~10:2 ,QIL 1:6] load dialect 'presto' class not found
        at net.hasor.dataql.runtime.inset.OpcodesPool.doWork(OpcodesPool.java:51)
        at net.hasor.dataql.runtime.mem.RefLambdaCall.call(RefLambdaCall.java:54)
        at net.hasor.dataql.runtime.mem.RefCall.invokeMethod(RefCall.java:50)
        at net.hasor.dataql.runtime.inset.CALL.doWork(CALL.java:57)
        at net.hasor.dataql.runtime.inset.OpcodesPool.doWork(OpcodesPool.java:45)
        at net.hasor.dataql.runtime.QueryImpl.execute(QueryImpl.java:83)
        at net.hasor.dataql.runtime.QueryImpl.execute(QueryImpl.java:37)
        at net.hasor.dataql.Query.execute(Query.java:50)
        at net.hasor.dataway.service.ApiCallService._doCall(ApiCallService.java:145)
        at net.hasor.dataway.service.ApiCallService.doCallWithoutError(ApiCallService.java:55)
        at net.hasor.dataway.web.PerformController.doPerform(PerformController.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.hasor.web.invoker.InvokerCaller.lambda$invoke$0(InvokerCaller.java:108)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:46)
        at net.hasor.dataway.service.InterfaceUiFilter.doInvoke(InterfaceUiFilter.java:71)
        at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:98)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41)
        at net.hasor.dataway.authorization.InterfaceAuthorizationFilter.doInvoke(InterfaceAuthorizationFilter.java:93)
        at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:98)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41)
        at net.hasor.dataway.authorization.AdminUiAuthorization.doInvoke(AdminUiAuthorization.java:90)
        at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:98)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:43)
        at net.hasor.web.render.RenderInvokerFilter.doRenderInvoker(RenderInvokerFilter.java:118)
        at net.hasor.web.render.RenderInvokerFilter.doInvoke(RenderInvokerFilter.java:74)
        at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:98)
        at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41)
        at net.hasor.web.invoker.InvokerCaller.invoke(InvokerCaller.java:117)
        at net.hasor.web.invoker.InvokerCaller.invoke(InvokerCaller.java:76)
        at net.hasor.web.invoker.InvokerContext.lambda$null$5(InvokerContext.java:117)
        at net.hasor.web.invoker.HttpParameters.executeWorker(HttpParameters.java:50)
        at net.hasor.web.invoker.InvokerContext.lambda$genCaller$6(InvokerContext.java:116)
        at net.hasor.web.startup.RuntimeFilter.doFilter(RuntimeFilter.java:125)
        at net.hasor.web.startup.RuntimeFilter.doFilter(RuntimeFilter.java:114)
        at net.hasor.spring.beans.RuntimeFilter2Interceptor.preHandle(RuntimeFilter2Interceptor.java:38)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:141)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: load dialect 'presto' class not found
        at net.hasor.db.dialect.SqlDialectRegister.findOrCreate(SqlDialectRegister.java:117)
        at net.hasor.dataql.fx.db.runsql.SqlFragment.usePageFragment(SqlFragment.java:236)
        at net.hasor.dataql.fx.db.runsql.SqlFragment.runFragment(SqlFragment.java:214)
        at net.hasor.dataql.runtime.mem.RefFragmentCall.call(RefFragmentCall.java:96)
        at net.hasor.dataql.runtime.mem.RefCall.invokeMethod(RefCall.java:50)
        at net.hasor.dataql.runtime.inset.CALL.doWork(CALL.java:57)
        at net.hasor.dataql.runtime.inset.OpcodesPool.doWork(OpcodesPool.java:45)
        ... 79 common frames omitted
^A^A

**Comment by zycgit** [comment]
字典方言不存在，你按照 文档和源码上的方式加一个 presto 分页字典。
